### ISSUE TITLE
(FIXED) I'm getting a warning/error for tab completing the /whereis command

### ISSUE THREAD

**Issue by MrBsng** [VarChar42/Spigot-WhereIs#5]
It happens even if I do a space and start typing out the player character by character.
https://user-images.githubusercontent.com/48810871/200442821-ec789c54-24e2-4340-a209-973b088ab770.mp4

Here is the text from my console.
/*
[16:05:00 ERROR]: Exception when TBYT attempted to tab complete whereis tby
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/whereis tby' in plugin WhereIs v2.1.4
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.tabCompleteCommand(CraftServer.java:2236) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.tabComplete(CraftServer.java:2208) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[paper-1.19.jar:git-Paper-81]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Paper-81]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[paper-1.19.jar:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[paper-1.19.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:870) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "guess" is null
	at me.varchar42.whereis.commands.WhereIs.onTabComplete(WhereIs.java:88) ~[Spigot-WhereIs-2.1.4.jar:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 22 more
*/

Similar Output found here below.
https://www.spigotmc.org/threads/tabcompleter-error-for-multiple-arguments.399785/ 

Let me know if this is a Paper Server or Bukkit Error if this cannot be fixed on your end.
I'm running a Paper server on 1.19.0.

**Comment by VarChar42** [comment]
Currently 1.19 is not supported by the plugin. I am going to fix that in the coming few days.

**Comment by VarChar42** [comment]
I could not exactly replicate your issue, but users which username cannot be resolved will now get ignored by tabcomplete, instead of throwing an Exception.

**Comment by MrBsng** [comment]
Ok, i'll check out the new release and let you know.

**Comment by MrBsng** [comment]
> I could not exactly replicate your issue, but users which username cannot be resolved will now get ignored by tabcomplete, instead of throwing an Exception.

The bug is fixed now. No more errors when tab completing on java edition.
